server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hellxz/SpringCloudlearn
          search-paths: config-repo
          username: username  #账号密码写真实的快一些我觉得，不使用也能访问有点慢
          password: password
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
